/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dfe2f3",
        "on-error": "#690005",
        "secondary-fixed-dim": "#00e297",
        "primary-container": "#00aaff",
        "secondary-container": "#00ffab",
        "on-secondary-container": "#007149",
        "surface-bright": "#353946",
        "outline-variant": "#3e4851",
        "surface-container-highest": "#313442",
        "on-tertiary-container": "#5a008a",
        "on-primary-fixed-variant": "#004b73",
        "secondary-fixed": "#4dffb2",
        "on-primary-container": "#003c5d",
        "on-surface": "#dfe2f3",
        "on-secondary-fixed": "#002112",
        "error": "#ffb4ab",
        "surface-tint": "#93ccff",
        "on-secondary": "#003822",
        "surface-container-high": "#262a37",
        "background": "#0f131f",
        "on-tertiary": "#4e0078",
        "surface": "#0f131f",
        "primary": "#93ccff",
        "tertiary-fixed-dim": "#e4b5ff",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#f4d9ff",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#2f004b",
        "surface-container-lowest": "#0a0e1a",
        "tertiary": "#e4b5ff",
        "tertiary-container": "#ce81ff",
        "on-tertiary-fixed-variant": "#6f00a9",
        "on-primary-fixed": "#001d31",
        "surface-dim": "#0f131f",
        "primary-fixed": "#cce5ff",
        "outline": "#88929d",
        "secondary": "#f4fff5",
        "on-surface-variant": "#bec7d3",
        "on-background": "#dfe2f3",
        "on-primary": "#003351",
        "surface-container": "#1b1f2c",
        "inverse-primary": "#006398",
        "surface-variant": "#313442",
        "primary-fixed-dim": "#93ccff",
        "surface-container-low": "#171b28",
        "inverse-on-surface": "#2c303d",
        "on-secondary-fixed-variant": "#005234"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}
